# Generated by Django 2.2.1 on 2020-01-30 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leavemanagementsystem.helpers.fancy_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(db_index=True, default=leavemanagementsystem.helpers.fancy_generator.fancy_id_generator, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('notification', models.TextField()),
                ('email', models.CharField(blank=True, max_length=256)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification', models.TextField(default='trip')),
                ('status', models.CharField(blank=True, default='Pending', max_length=256)),
                ('leave_requestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requestor', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Request')),
            ],
        ),
    ]
