# Generated by Django 2.2.1 on 2020-01-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='number_of_days',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
