# Generated by Django 2.2.1 on 2020-01-30 18:04

from django.db import migrations, models
import django.db.models.deletion
import leavemanagementsystem.helpers.fancy_generator


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20200130_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveNotifications',
            fields=[
                ('id', models.CharField(db_index=True, default=leavemanagementsystem.helpers.fancy_generator.fancy_id_generator, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, default='Pending', max_length=256)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Notification')),
            ],
        ),
    ]
