# Generated by Django 2.2.1 on 2020-01-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_approvenotifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApproveNotifications',
        ),
    ]
