# Generated by Django 2.2.1 on 2020-01-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_delete_approvenotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='classification',
            field=models.TextField(default='leave_requests'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=256),
        ),
    ]
