# Generated by Django 3.0.2 on 2020-01-28 10:41

from django.db import migrations, models
import leavemanagementsystem.helpers.fancy_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(db_index=True, default=leavemanagementsystem.helpers.fancy_generator.fancy_id_generator, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Regular User', max_length=256)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
