# Generated by Django 2.2.1 on 2020-01-30 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leavemanagementsystem.helpers.fancy_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(db_index=True, default=leavemanagementsystem.helpers.fancy_generator.fancy_id_generator, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('leave_request', models.CharField(default='Pending', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_days', models.DateTimeField()),
                ('requestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
