# Generated by Django 2.2.1 on 2020-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='number_of_days',
            field=models.CharField(max_length=200),
        ),
    ]
