# Generated by Django 2.2.1 on 2020-01-31 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20200130_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='leave_request',
        ),
    ]
