# Generated by Django 2.2.1 on 2020-01-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptednotifications',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
