# Generated by Django 2.2.1 on 2020-01-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_acceptednotifications_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApproveNotifications',
        ),
    ]
